[tool.ruff]
line-length = 100

exclude = [
    "**/constants.py",
    "**/*.ipynb",
]

[tool.ruff.lint]
select = ["E", "F", "I", "B"]  # Pyflakes, pycodestyle, isort, bugbear

[tool.ruff.format]
quote-style = "double"
